# Generated by Django 5.2 on 2025-04-08 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals', models.CharField(max_length=1000)),
                ('meals_description', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=5, max_digits=200)),
                ('meals_type', models.CharField(choices=[('starters', 'Starters'), ('salads', 'Salads'), ('main dishes', 'Main Dishes'), ('desserts', 'Desserts')])),
                ('status', models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=1)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('author_cook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
