# Generated by Django 5.2 on 2025-04-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='author_cook',
            new_name='author_cook_user',
        ),
    ]
